language: node_js
node_js:
  - '0.8'
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-toasterplugin' ]; then cd .. && eval "mv $currentfolder generator-toasterplugin" && cd generator-toasterplugin; fi

